version: 0.0 
os: linux
files:
  - source: /
    destination: /home/ubuntu/EC2-Deploy-Test
permissions:
  - object: /home/ubuntu/EC2-Deploy-Test
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: deploy.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy.sh
      timeout: 600
      runas: root