version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/EC2-Deploy-Test
permissions:
  - object: /home/ubuntu/EC2-Deploy-Test
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 1200
      runas: root