version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/EC2-Deploy-Test
hooks:
  ApplicationStop:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu